'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* * * * * * * C O M P L E T E D * * * * * *'''
a = 0
b = 1
new_term = 0
fib_seq = []
while new_term<4000000:
    fib_seq.append(new_term)
    new_term = a + b
    a = b
    b = new_term
sum = 0
for k in fib_seq:
    if k%2==0:
        sum+=k
print(fib_seq)
print(sum)
